name: 'Python Test'
description: "A Github action to run pytest Tests"

inputs:
  python_version:
    description: 'The version of Node.js to use'
    required: true
    default: '14'
  python_path:
    description: 'path of the application'
    required: true
  coverage:
    description: 'percentage of test coverage required to pass'
    required: true

runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        shell: bash
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        shell: bash
        run: |
          pytest
  # - name: Checkout code
  #   uses: actions/checkout@v3

  # - name: Use Node.js
  #   uses: actions/setup-python@v2
  #   with:
  #     node-version: ${{ inputs.python_version }}

  # - id: test
  #   shell: bash
  #   working-directory: ${{  inputs.python_path  }}
  #   run: |
  #     sh ${{github.action_path}}/src/main.sh ${{  inputs.coverage  }}


outputs:
    test_coverage:
      description: "percentage of test coverage"
      value: ${{ steps.test.outputs.test_coverage }}
    test_status:
      description: "status of the test"
      value: ${{ steps.test.outputs.test_status }}
