name: 'Test Composite Action'
description: 'Test Composite Action'
inputs:
  environment:
    description: 'Running Environment'     
    required: true 
  system:
    description: 'System'     
    required: true 
  sub_system:
    description: 'Sub_System'     
    required: true 
  stack:
    description: 'Stack'     
    required: true 
  docker_image_name:
    description: 'docker image name'
    required: true
  docker_image_tag:
    description: 'docker image tag'
    required: true
  repo_url:
    description: 'URL of docker repo'
    required: true
  aws_role_arn:
    description: "AWS Role to Assume"
    required: true
  aws_region:
    description: "AWS Region"
    required: true



runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{  inputs.aws_role_arn  }}
        aws-region: ${{  inputs.aws_region  }}
        # aws-access-key-id: ${{inputs.AWS_ACCESS_KEY_ID}}
        # aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Login to Amazon ECR
      id: login-ecr        
      uses: aws-actions/amazon-ecr-login@v1

    - id: build
      shell: bash
      run: |
        sh ${{github.action_path}}/src/main.sh \
          -t ${{  inputs.docker_image_tag  }} -n ${{  inputs.docker_image_name  }} -r ${{  inputs.repo_url  }}


outputs:
    docker_image_name:
      description: "Name of the docker image"
      value: ${{ steps.build.outputs.docker_image_name }}
    docker_image_details:
      description: "Details of the docker image"
      value: ${{ steps.build.outputs.docker_image_details }}